### PR TITLE
Improvement to the layer panel

### PR DESCRIPTION
**Pull request by Nemikolh**
- [x] Automatically focus the map after a layers has been selected. This allow to press `P` right after a click on a layer.
- [x] Highlight the currently selected layer
- [x] Show a preview of the layer
- [x] ~~Reorder layer with drag n drop?~~
- [x] ~~Add to the currently empty options section to show the other layers with a different opacity than the one that is active.~~

### CODE REVIEW

**Comment by Nemikolh** [comment]
@lethom, @Azamung We have the preview! :sunny: 

layers_preview

Note that the PR is not ready yet:
- [x] the brush is now somehow invisible
- [x] the previews needs to be updated whenever the map is changed (for now you need to select them to see a change)

**Comment by Nemikolh** [comment]
@lethom : If you can wait a little before submitting the next JdD, so that I have time to finish the last two tasks (from my last comment), it would be awesome!

**Comment by Nemikolh** [comment]
@lethom : Ready for review sir!

**Comment by lthms** [comment]
Okay so I tested the thing and I think it is great! Just a suggestion: I found the order of the layer very confusing (the upper one is under the lower one). Would you mind switch them? Also maybe you could highlight a little more the selected layer?

It’s just cosmetic, the code works great and you can merge if you want to do that in another PR.

**Comment by Nemikolh** [comment]
@lethom Done! :smiley:

**Comment by lthms** [comment]
Tested it, loved it, merged it.

**Comment by lthms** [comment]
Travis yells a little: https://travis-ci.org/GreenPix/dilia/jobs/158524276 (but somehow it is green x))

**Comment by Nemikolh** [comment]
Yeah, I tried to solve that issue but couldn't understand why (see #30). I think this is a bug in the closure compiler. Thanks for the reminder though, I'll submit a PR that use UglifyJS instead by default. It produce bigger output than closure but that still much better than nothing.

Thanks for the review!

**Pull request merged**
