### PR TITLE
AaribaScript editor support + Project setup

### PR DESCRIPTION
**Pull request by Nemikolh**
## AaribaScript editor + Project setup

This PR implement partially RSP-1 (GreenPix/meta#1) within the editor to allow easy debug/implementation and more importantly propagate the changes up to the back-end that Vesperae will then consume at run-time.
## Tasks:
- [x] Basic setup of the editor
- [x] Autocompletion
  - [x] Autocomplete on globals
  - [ ] ~~Autocomplete on locals~~
- [x] Syntax highlighting
  - [x] Support for comments
  - [x] Highlight all other tokens
- [x] PEGjs interpreter
  - [x] Support for expression
  - [x] Support for `if`
  - [x] Support for `sin`, `cos`, `rand`, `%`, `max` and `min`.
  - [x] Support for comments
  - [x] Fix bugs with error reporting
  - [x] Support for default operator: `?`
- [x] Inject PEG failure as lint in the editor
- [x] Fold `if`
- [ ] ~~Fold comments~~.
- [x] Add behavior that automatically add a `}` after pressing enter for a `if`
- [x] Back-end script management
  - [x] creation
  - [x] listing
  - [x] edition 
  - [x] socket.io for lock/free on resources (bonus: update read-only content) 
- [x] Basic user authentication (to have a real end to end solution)
- [x] Front-end management
  - [x] Open a script
  - [x] Commit a revision
  - [x] Create a script
  - [x] Update read-only content modified by user x
  - [x] Sync file list: length and lock state

### CODE REVIEW

**Comment by ghost** [comment]
I don't think setting the milestone _before merging_ is a good idea. What if you do not have time to finish this PR before the next monthly recap? You always can set a new milestone of course, but from my point of view, milestone should be add after merging. It's more error-free.

**Comment by Nemikolh** [comment]
I understand your point for future PR. Here we can leave the milestone as it is going to be merged soon (should be done by the end of the week).

Thanks for the feedback !

**Comment by ghost** [comment]
That's great news! Before merging it, can you ping me? I would love to test your work, in order to help and (maybe, maybe not) find potential bugs.

**Comment by Nemikolh** [comment]
Yes of course! :smiley: I'll keep you up to date.

**Comment by ghost** [comment]
I just have a question: which AaribaScript are you implementing, since we still do not know entirely its specs and purpose?

(don't get this the wrong way: it's a good thing you keep going on that, I'm just wondering, that's all)

**Comment by Nemikolh** [comment]
Yep no problem!

I'm implementing what I remember we kinda agreed on :santa: .
It's mainly as a pretext to play with PEG.js. While I'm coding, I'm also learning about webpack. And I realised my code could be much cleaner. Also the errors messages reported are kind of buggy/confusing.
I intend to refactor the interpreter in a later pull request, and at that point I hope we will have agreed on a more stable version of the RSP-1.

**Comment by ghost** [comment]
Great! I just removed the milestone, as I think we will be a little short for this sunday!

**Comment by Nemikolh** [comment]
Yeah I'm not sure I will finish that before the end of the week-end. Are you still willing to try at some point? I might get a "usable" version by the end of tomorrow.

**Comment by ghost** [comment]
To be honest, I'd rather not. I still have to write the recap and I feel I will have enough to say already just with what we merged in `meta` and what you've done before I wrote the previous recap.

I just have to find some time to do that, probably tomorrow at lunchtime.

**Comment by Nemikolh** [comment]
Ok no worries! If you need some help for reviewing or anything let me know.

**Comment by ghost** [comment]
Authentication in a PR that deals with AaribaScript? Isn’t it a little out of scope?

**Comment by Nemikolh** [comment]
True. I needed the concept of user to do the script saving, so that's why I included that in this PR.
Is it okay for you or would you prefer the PR to be split in two ?
I could simplify this PR by limiting the content of this PR to only the client side of things and create a new one that does basic user authentication and script saving. What do you prefer ?

**Comment by Nemikolh** [comment]
Note that more generally this PR includes many things that are not only limited to aariba script such as webpack configuration, scss, font-awesome and so on. In the future having a PR like this, that includes many things off topic probably won't happened again as after that, all the main setup will be there.

**Comment by ghost** [comment]
>  In the future having a PR like this, that includes many things off topic probably won't happened again as after that, all the main setup will be there.

This only means using the PR system for this project has been done too early. That’s not a big deal, do not worry and keep things like that. Hopefully and as you just said, with a more mature code base, atomic PR will become more natural.

**Comment by Nemikolh** [comment]
Glad to hear it ! :smiley: 
You are saving me from a huge fight with git ! x)
I'll ping you for a quick review when the PR is ready. I hope to get it ready by the end of the week.

**Comment by ghost** [comment]
> You are saving me from a huge fight with git ! x)

There is no reason to fight. Just embrace the dark side.

**Comment by Nemikolh** [comment]
@Ikyushii I intend to merge this (now really long) PR after review before the next recap. If you would like to discuss what to say about it, ping me by email and we can discuss it.

**Comment by ghost** [comment]
@Nemikolh : It’s a huge PR indeed. I will try to review this as soon as possible and yes, we’ll need to discuss a little :).

**Comment by Nemikolh** [comment]
@Ikyushii Yeah it is. x) Hopefully, the actual logic is relatively thin. Most of the PR is really about the project set up. If I have time, I'll try to set up an heroku instance to play and discuss around it.

**Comment by Nemikolh** [comment]
@Ikyushii Do you think you could a quick review of the PR? The PR is ready. I would like to merge it and move on something else.

**Pull request merged**
