### PR TITLE
Open map

### PR DESCRIPTION
**Pull request by Nemikolh**
- [x] possibility to open a map
- [x] visualize the preview of the map
- [x] submit the preview when committing the map (front-end)

### CODE REVIEW

**Comment by lthms** [comment]
> The problem with this version: the original canvas size is used.
> Maybe resize it, update the viewport and hope for the best?

I was probably expecting the canvas API has a way to resize one canvas. Is that so?

**Comment by Nemikolh** [comment]
Yes, the canvas do have a way to resize it!

My concerns is that, in order to be effective, it probably require an animation frame. So this means that the change would be visible from the user (he will see the canvas blinking more likely). And this is something that I wanted to avoid. Right now, it doesn't do it, because I don't have to wait for an animation frame.

One way to solve that problem is to hide entirely the map while the commit dialog is opened.

Another solution would be to do a readPixel, then do the rendering in another canvas. But I would like to avoid that if possible because it feels really hacky (more specifically the code would really be way more complex).

Finally another solution is to do the png encoding in JavaScript using a library. This is also doable but feels overkill.

**Comment by Nemikolh** [comment]
There's still a bug that needs to be fixed: If the map was created with only one layer. When it is reopened, it only has one layer. Besides, the visualization is kinda broken. There's a synchronisation problem between the model and the rendered version. I'll have a look tomorrow.

**Comment by Nemikolh** [comment]
@lethom I think I have fixed most of the issues now. Please let me know what you think and if you are satisfied you can submit an approved review and merge the PR.

**Comment by lthms** [comment]
I will try this as soon as I can. Thanks for your work.

**Review by lthms — APPROVED** [review]
Okay, so I found one last thing. The open map panel does not update itself ; I need to refresh the page for my new map to appear in it. Otherwise, it’s perfect. I approve the change because I think this last issue can be addressed later.

**Comment by Nemikolh** [comment]
Oh yeah, I intend to solve that problem for everything in another PR. I'm glad that everything worked! :-)

**Pull request merged**
