### PR TITLE
Cleanup unused code

### PR DESCRIPTION
**Pull request by Nemikolh**
Also addressed marked tslint hack explicitly to be removed. (Just to remind me when I start doing the save map task).

### CODE REVIEW

**Comment by lthms** [comment]
That is a cut!

**Comment by Nemikolh** [comment]
This PR is ready to land! :) There's still cleanup we can do, but I'll focus my work on the commit action to save a map on the server. Please let me know if you have any questions / concerns.

**Comment by lthms** [comment]
Unfortunately it is hard for me to do a proper code review as I am not used to dilia code and it is an heavy modification. This is why I have just tested. Here is what I did:
- I built both the server and the client in a fresh environment: _OK_
- I created a new user account: _OK_
- I signed in with this account: _OK_
- I created a new map: _OK_
- I zoom the empty map: _OK_
- I painted with on tile: _OK_
- I zoom in and out again: _OK_
- I play with the palette: _OK_

As far as I am concerned, we are ready to go, so I’m merging it right now. Congrats and thanks!

**Comment by Nemikolh** [comment]
Arf, I'm sorry. I wanted to have all the big clean up in just one PR. So
that it's easy to go back to it. But it's not nice for reviewing. :-|
I'm glad you tried it out! Thanks for doing it!

**Comment by lthms** [comment]
Don’t be sorry, you did great (:

**Pull request merged**
