### PR TITLE
Improve build system

### PR DESCRIPTION
**Pull request by Nemikolh**
This simplify the build system a little. It also remove our dependency on gulp which is good as well.
I haven't tried yet, but we need to make sure that a fresh install works without problems and that a production build generate all files within the `build` directory.
- [ ] Have a script to start the server being generated in the build folder
- [ ] Have a `package.json` generated as well for the server with only server dependencies (?)

(Not sure if the second point is useful)

### CODE REVIEW

**Comment by lthms** [comment]
This PR leads to a question of mine: is there any way to say tsc in a dependency which therefore will be fetched by `npm install` then use this fresh tsc compiler?

**Comment by lthms** [comment]
I rebased your branch against `master` and tested it: it works and you can merge it if you will as soon as travis turns green.

**Comment by Nemikolh** [comment]
Yes you can! When a dependency provides executables, they're available by name to npm scripts and on the command line like so:`$(npm bin)/<name>`. So, in the case of `tsc`, it is provided by the `typescript` dependency and you can access it as `$(npm bin)/tsc --help`

**Comment by Nemikolh** [comment]
Thanks!

**Pull request merged**
