### PR TITLE
Fix regressions

### LINKED ISSUE #28: The navigation bar is broken
Except for the sign out button, it seems nothing is working as it should. In particular, it is not possible to access the aariba script editor through it.

### PR DESCRIPTION
**Pull request by Nemikolh**
Should fix #28.

### CODE REVIEW

**Comment by Nemikolh** [comment]
There's a bug in the closure-compiler but I don't understand what's the problem. I'll try to fix it later.

**Comment by lthms** [comment]
Yay! I will test all of this tomorrow!

**Comment by lthms** [comment]
Okay, this is better! The navigation bar bug is gone.

The `Options` tab still does not work. Is it normal (maybe it is just not implemented and in this case, it is fine). I still cannot commit a map and I found myself unable to create a new map after a while of testing (even if I log out and sign in). But it is out of the scope of this PR.

Therefore I will merge, but we should keep talking.

**Comment by lthms** [comment]
Also, I found a strange bug where the right-half of my newly created map was painted with the first tiled of my uploaded chipset. I am not sure who I did this and was not yet able to reproduce it. Does it ring a bell to you?

**Comment by Nemikolh** [comment]
Thanks a lot for your review! This is really valuable. :-)
- the `option` is indeed doing nothing at the moment, I was intending to put things like turn on/off the grid but I don't like the current design. So it might be removed entirely. 
- I need to look into the map commit issue. I think I know why the map editor is broken after log out /login but not sure how to solve it. 
- This last bug is quite interesting! I had no idea this could happen.

**Comment by lthms** [comment]
I can at least do that, since I do not code right now.

**Pull request merged**
