### PR TITLE
build: use the tsc provided by `npm install`

### PR DESCRIPTION
**Pull request by lthms**
The tsc compiler is provided by the `typescript` dependency

### CODE REVIEW

**Comment by lthms** [comment]
Note: rather than merge using the default option (and create a merge commit), we should use the [squash & merge feature](https://github.com/blog/2141-squash-your-commits) of github.

**Comment by Nemikolh** [comment]
Hmm, that's already the case. Npm expose the binaries to the npm scripts so this change is unnecessary. Are you in a situation where you have installed typescript globally?

**EDIT:** Actually that might be the only reason to do this change, however, it does not work on windows. So I would prefer to stick to the current solution which is portable.

**Comment by Nemikolh** [comment]
So I've tried the following:
**Package.json**

``` json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "fun": "tsc --version"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "1.8.10"
  }
}
```

Then

``` bash
npm install -g typescript@1.8.9
npm install
npm run fun
```

Here is the result:

``` bash
vagrant@vagrant-ubuntu-trusty-64:~/test$ tsc --version
Version 1.8.9
vagrant@vagrant-ubuntu-trusty-64:~/test$ npm run fun

> test@1.0.0 fun /home/vagrant/test
> tsc --version

Version 1.8.10
```

So the current setup is correct. :)

**Comment by lthms** [comment]
I am sorry for not replying earlier, I had a very busy week-end.

To answer your questions, the reason behind this PR was very simple and yet very strange: even if the `npm run build-server` command have been working for a while, I found myself in a situation where the tsc binary couldn’t be found, even after a `npm install`.

Yet, it _was working before_, so probably the error was mine. Therefore you probably did the good thing by closing this PR.

**Comment by Nemikolh** [comment]
Erg, that's weird. Which version of node and npm are you running?

The CI only check for the LTS version of node / npm and the unstable (6) version. 

We might want to add to the README the versions we support.

**Comment by lthms** [comment]
Well as I said, it worked before, I probably did something wrong which had nothing related to npm or node :\ I will try to investigate today.

**Pull request closed without merging**
